package:
  name: conjure-python-lib
  version: {{ GIT_VERSION_STRING.replace("-", "_") }}

source:
  path: ../python

build:
  noarch_python: True

requirements:
  build:
    - python
    - setuptools
    - pytest
    - requests
    - typing

  run:
    - python
    - requests
    - typing
