package:
  name: conjure-python-lib
  version: {{ GIT_VERSION_STRING.replace("-", "_") }}

source:
  path: ../python

build:
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - enum34
    - python
    - requests
    - typing

test:
  imports:
    - conjure
    - httpremoting
