package:
  name: conjure-python-lib
  version: "{{ PACKAGE_VERSION }}"

source:
  path: ../python

requirements:
  build:
    - python {{ python }}
    - setuptools

  run:
    - python
    - enum34 # [py<34]
    - requests
    - typing

test:
  imports:
    - conjure
    - httpremoting
